import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useEffect } from "react";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // get answers related to question
  const questions = api.exam.getAllQuestionsAndAnswers.useQuery();
  const exams = api.exam.getAllExams.useQuery();
  const questionList = questions.data;
  console.log(questions.data)
  //console.log(exams.isSuccess)
  //console.log(questions.isSuccess)
  // handleSubmit = (event) => {
  //   event.preventDefault();
  //   //console.log(event.target[0].value)
  // }
  const userAnswers = [
    
  ];

  const useIsCorrect = (id : string, isCorrect : boolean) : void => {
    console.log(id)
    console.log(isCorrect)
    if(isCorrect==true){
      console.log("Correct answer")
        const correctAnswer = document.getElementById(id);
        console.log("correctAnswer: " + " " +  correctAnswer?.classList)
        correctAnswer?.classList.add("bg-green-500");
    }
  };

  const handleSubmit = (event : Event) => {
    event.preventDefault(); // Prevent form submission
    if (!event.target) return;
  };

  return (
    <>
      <Head>
        <title>Exams - prepare yourself for the hardest exams in your life</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-slate-950 text-sm">
        <div className="header flex items-center justify-center text-whit py-4">
          <div className="container flex justify-between text-slate-100 px-4">
          <div>Exams ✅</div>
          <div className="flex gap-2">
            <div className="cursor-pointer">Test 1 pytanie</div>
            <div className="cursor-pointer">Test 15 pytan</div>
            <div className="cursor-pointer">Test 100 pytan</div>
          </div>
          </div>
        </div>
        <div className="hero flex items-center justify-center text-whit py-4">
        <div className="CTA-HERO text-slate-200 mt-24">
            <h1 className="text-6xl font-bold">Begin your niskopoziomowe journey 😊</h1>
        </div>
  
          </div>
          <div className="flex justify-center">
            <div className="container">
              <form className="formExam text-slate-50" onSubmit={handleSubmit}>
                {questionList?.map((q) => (
                  <div key={q.id} className="px-4 py-4 border rounded-xl my-4 mx-4">
                    <div>
                    {q.body}
                    </div>
                    {q.answers.map((a) => (
                    <div key={a.identifier} onClick={useIsCorrect(`div-${a.identifier}`, a.isCorrect)}  id={`div-${a.identifier}`}>
                      <input type="radio" name={q.id} value={a.identifier} id={`answer-${a.identifier}`}  className="mr-2" />
                      <label htmlFor={`answer-${a.identifier}`}>{a.body}</label>
                    </div>
                  ))}
             
                  </div>
                  
                ))}
                <button className="bg-slate-900 text-slate-50 px-4 py-2 rounded-xl mt-4 mx-4" type="submit">Check your answers</button>
              </form>
            </div>
          </div>

      </main>
    </>
  );
};

export default Home;
